# -*- coding: utf-8 -*-
"""Day_72.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19WjJOtRFiqJDziUYLDJPKRAe_K4AnhXr
"""



import pandas as pd

df=pd.read_csv('salaries_by_college_major.csv')
df.tail()

df.shape

df.columns

df.isna()

clean_df=df.dropna()
clean_df.tail()

clean_df['Starting Median Salary'].idxmax()

clean_df['Undergraduate Major'].loc[43]

clean_df['Undergraduate Major'][43]

clean_df.loc[43]

"""Highest Mid-career salary

"""

clean_df['Mid-Career Median Salary'].idxmax()

clean_df.loc[8]

clean_df['Starting Median Salary'].idxmin()

clean_df.loc[49]

clean_df['Mid-Career Median Salary'].idxmin()

clean_df.loc[18]



"""Calculations

"""

difference_prec=clean_df['Mid-Career 90th Percentile Salary']-clean_df['Mid-Career 10th Percentile Salary']

clean_df.insert(1, 'Spread', difference_prec)
clean_df.head()

low_risk=clean_df.sort_values('Spread')
low_risk

low_risk.tail()

high_potential=clean_df.sort_values('Mid-Career 90th Percentile Salary')
high_potential.tail()

clean_df.groupby('Group').count()

clean_df.groupby('Group').mean('Starting Median Salary')

pd.options.display.float_format = '{:,.2f}'.format

